import type { Capability } from "@/lib/capabilities";
import { getCapability } from "@/lib/capabilities";
import type { Locale } from "@/lib/i18n";

type CapabilityTranslation = Pick<Capability, "title" | "description" | "overview" | "scope" | "delivery">;

export const CAPABILITY_OG_IMAGE_ALT: Record<Locale, string> = {
  en: "Illuminated industrial processing facility at dusk",
  ru: "Освещённый промышленный технологический комплекс в сумерках",
  tr: "Akşam saatlerinde aydınlatılmış endüstriyel proses tesisi",
  kz: "Кешкі уақытта жарықтандырылған өнеркәсіптік технологиялық кешен",
};

const TRANSLATIONS: Record<Exclude<Locale, "en">, Record<string, CapabilityTranslation>> = {
  ru: {
    "construction-site-works": { title: "Строительные и площадочные работы", description: "Координированные гражданские, конструктивные и монтажные работы для коммерческих и промышленных проектов.", overview: "KAZENCO координирует определённые строительные пакеты: от подготовки площадки и сопряжения фундаментов до монтажа металлоконструкций и вспомогательной инфраструктуры. Работы планируются с учётом утверждённого объёма, требований доступа и правил HSE проекта.", scope: ["Поддержка гражданских работ и фундаментов", "Монтаж металлоконструкций", "Поддержка трубопроводной инфраструктуры", "Координация HSE на площадке"], delivery: [{ title: "Анализ объёма", description: "Проверка чертежей, сопряжений, ограничений площадки и необходимой документации." }, { title: "Планирование работ", description: "Координация ресурсов, последовательности, доступа и требований безопасности." }, { title: "Выполнение на площадке", description: "Выполнение согласованных работ с контролем прогресса и качества." }, { title: "Передача", description: "Закрытие пакета по утверждённому объёму и подтверждающим документам." }] },
    "fit-out-furnishing": { title: "Отделка и оснащение", description: "Комплексные пакеты внутренней отделки и оснащения офисов, вахтовых посёлков, гостиниц и эксплуатационных объектов.", overview: "Отделка, поставка мебели и монтаж координируются как единый пакет. Это сокращает разрывы между внутренними работами, закупками, перевозкой, расстановкой и окончательной передачей.", scope: ["Внутренняя отделка", "Офисная и вахтовая мебель", "Доставка и монтаж", "Финальная расстановка и передача"], delivery: [{ title: "Анализ требований", description: "Согласование ведомостей помещений, планировок, отделки и требований к мебели." }, { title: "Координация пакета", description: "Согласование отделочных работ, закупок и последовательности доставки." }, { title: "Монтаж", description: "Доставка, сборка и размещение утверждённого интерьерного и мебельного пакета." }, { title: "Завершение", description: "Проверка финальной расстановки и закрытие оставшихся пунктов передачи." }] },
    "industrial-procurement-supply": { title: "Промышленные закупки и поставки", description: "Проектный подбор и доставка технических материалов по спецификациям клиента и требованиям к документации.", overview: "KAZENCO анализирует требования проекта, координирует производителей и формирует пакеты поставки с учётом спецификации, количества, документации и места доставки. Итоговое соответствие подтверждается по каждому утверждённому запросу.", scope: ["Анализ технических требований", "Координация производителей", "Документация MTC и CoC", "Планирование доставки"], delivery: [{ title: "Технический анализ", description: "Проверка спецификаций, количеств, стандартов и требуемой документации." }, { title: "Подбор поставщиков", description: "Координация подходящих производителей и коммерческих условий поставки." }, { title: "Документация", description: "Комплектация согласованных сертификатов, записей и документов на материалы." }, { title: "Доставка", description: "Планирование упаковки, перевозки и доставки по утверждённому графику." }] },
    "environmental-geosynthetic-works": { title: "Экологические и геосинтетические работы", description: "Защитные грунтовые системы и геосинтетические решения для промышленной и гражданской инфраструктуры.", overview: "Защитные покрытия, подготовка основания и изоляция координируются с заданной конструкцией площадки и последовательностью монтажа. Объём согласуется со смежными гражданскими и конструктивными работами для непрерывности рабочего фронта.", scope: ["Системы защитной облицовки грунта", "Защитные слои основания", "Изоляционные работы", "Поддержка монтажа"], delivery: [{ title: "Анализ системы", description: "Проверка состава слоёв, сопряжений и зоны монтажа." }, { title: "Планирование материалов", description: "Координация утверждённых материалов, количеств и готовности рабочего фронта." }, { title: "Укладка", description: "Последовательный монтаж согласованных защитных слоёв со смежными работами." }, { title: "Закрытие", description: "Проверка завершённых участков и подтверждающих монтажных записей." }] },
  },
  tr: {
    "construction-site-works": { title: "İnşaat ve Saha İşleri", description: "Ticari ve endüstriyel projeler için koordineli inşaat, yapısal ve montaj işleri.", overview: "KAZENCO; saha hazırlığı ve temel arayüzlerinden çelik yapı montajı ve destek altyapısına kadar tanımlı inşaat paketlerini koordine eder. Uygulama, onaylı kapsam, erişim gereksinimleri ve proje HSE kurallarına göre planlanır.", scope: ["İnşaat işleri ve temel uygulamaları", "Çelik yapı montajı", "Boru hattı altyapı desteği", "Saha HSE koordinasyonu"], delivery: [{ title: "Kapsam incelemesi", description: "Çizimlerin, disiplinler arası bağlantıların, saha kısıtlarının ve gerekli belgelerin doğrulanması." }, { title: "Uygulama planlaması", description: "Kaynakların, iş sırasının, erişimin ve güvenlik gereksinimlerinin koordinasyonu." }, { title: "Saha uygulaması", description: "Mutabık kalınan işlerin ilerleme ve kalite koordinasyonuyla tamamlanması." }, { title: "Teslim", description: "Paketin onaylı kapsam ve destekleyici kayıtlarla kapatılması." }] },
    "fit-out-furnishing": { title: "İnce İşler ve Mobilya Uygulamaları", description: "Ofisler, kamplar, konaklama ve işletme tesisleri için bütünleşik iç mekân tamamlama ve mobilya paketleri.", overview: "İnce işler, mobilya tedariki ve montajı tek teslimat paketi olarak koordine edilir. Böylece iç işler, satın alma, taşıma, yerleştirme ve nihai teslim arasındaki boşluklar azalır.", scope: ["İç mekân ince işleri", "Ofis ve kamp mobilyası", "Tedarik ve montaj", "Nihai yerleşim ve teslim"], delivery: [{ title: "Gereksinim incelemesi", description: "Mahal listeleri, yerleşimler, yüzeyler ve mobilya gereksinimlerinin doğrulanması." }, { title: "Paket koordinasyonu", description: "İnce işler, satın alma ve sevkiyat programının uyumlandırılması." }, { title: "Montaj", description: "Onaylı iç mekân ve mobilya paketinin teslimi, montajı ve yerleştirilmesi." }, { title: "Tamamlama", description: "Nihai yerleşimin gözden geçirilmesi ve açık teslim maddelerinin kapatılması." }] },
    "industrial-procurement-supply": { title: "Endüstriyel Tedarik ve Satın Alma", description: "Müşteri şartnameleri ve dokümantasyon gereksinimlerine uygun teknik malzemelerin proje bazlı satın alma ve tedariki.", overview: "KAZENCO proje gereksinimlerini inceler, üreticileri koordine eder ve talep edilen şartname, miktar, dokümantasyon ve teslimat konumuna göre tedarik paketleri hazırlar. Nihai uygunluk her onaylı talep için doğrulanır.", scope: ["Teknik gereksinim incelemesi", "Üretici koordinasyonu", "MTC ve CoC dokümantasyonu", "Teslimat planlaması"], delivery: [{ title: "Teknik inceleme", description: "Şartnamelerin, miktarların, standartların ve gerekli teslimat belgelerinin kontrolü." }, { title: "Tedarikçi ve üretici seçimi", description: "Uygun üreticilerin ve ticari tedarik koşullarının koordinasyonu." }, { title: "Dokümantasyon", description: "Mutabık kalınan sertifika, kayıt ve malzeme belgelerinin hazırlanması." }, { title: "Teslimat", description: "Paketleme, taşıma ve teslimatın onaylı programa göre planlanması." }] },
    "environmental-geosynthetic-works": { title: "Çevresel ve Geosentetik İşler", description: "Endüstriyel ve sivil altyapıyı destekleyen koruyucu zemin sistemleri ve geosentetik uygulamalar.", overview: "Koruyucu kaplama, alt zemin ve yalıtım uygulamaları tanımlı saha katmanları ve montaj sırasına göre koordine edilir. Çalışma sürekliliğini korumak için kapsam, ilgili inşaat ve yapısal işlerle uyumlandırılır.", scope: ["Zemin kaplama sistemleri", "Koruyucu alt zemin katmanları", "Yalıtım uygulamaları", "Montaj desteği"], delivery: [{ title: "Sistem incelemesi", description: "Belirtilen katman yapısının, arayüzlerin ve uygulama alanının doğrulanması." }, { title: "Malzeme planlaması", description: "Onaylı malzemelerin, miktarların ve çalışma alanı hazırlığının koordinasyonu." }, { title: "Uygulama", description: "Mutabık kalınan koruyucu katmanların komşu işlerle sıralı biçimde uygulanması." }, { title: "Kapanış", description: "Tamamlanan alanların ve montaj kayıtlarının incelenmesi." }] },
  },
  kz: {
    "construction-site-works": { title: "Құрылыс және алаң жұмыстары", description: "Коммерциялық және өнеркәсіптік жобаларға арналған үйлестірілген азаматтық, құрылымдық және монтаждық жұмыстар.", overview: "KAZENCO алаңды дайындау мен іргетас түйісулерінен бастап металл құрылымдарын орнату және қосалқы инфрақұрылымға дейінгі құрылыс пакеттерін үйлестіреді. Орындау бекітілген көлемге, қолжетімділік талаптарына және жоба HSE ережелеріне сәйкес жоспарланады.", scope: ["Азаматтық жұмыстар және іргетас қолдауы", "Металл құрылымдарын монтаждау", "Құбыр инфрақұрылымын қолдау", "Алаңдағы HSE үйлестіру"], delivery: [{ title: "Көлемді талдау", description: "Сызбаларды, түйісулерді, алаң шектеулерін және қажетті құжаттарды тексеру." }, { title: "Орындауды жоспарлау", description: "Ресурстарды, реттілікті, қолжетімділікті және қауіпсіздік талаптарын үйлестіру." }, { title: "Алаңда орындау", description: "Келісілген жұмыстарды прогресс пен сапаны үйлестіре отырып аяқтау." }, { title: "Тапсыру", description: "Пакетті бекітілген көлем мен растайтын жазбалар бойынша жабу." }] },
    "fit-out-furnishing": { title: "Әрлеу және жиһаздандыру", description: "Кеңселерге, вахталық қалашықтарға, қонақүйлер мен өндірістік нысандарға арналған кешенді интерьер және жиһаз пакеттері.", overview: "Әрлеу, жиһаз жеткізу және монтаж бір пакет ретінде үйлестіріледі. Бұл ішкі жұмыстар, сатып алу, тасымалдау, орналастыру және соңғы тапсыру арасындағы алшақтықты азайтады.", scope: ["Интерьерді әрлеу", "Кеңсе және вахталық жиһаз", "Жеткізу және монтаж", "Соңғы орналастыру және тапсыру"], delivery: [{ title: "Талаптарды талдау", description: "Бөлме тізімдерін, жоспарларды, әрлеуді және жиһаз талаптарын тексеру." }, { title: "Пакетті үйлестіру", description: "Әрлеу жұмыстарын, сатып алуды және жеткізу ретін сәйкестендіру." }, { title: "Монтаж", description: "Бекітілген интерьер мен жиһаз пакетін жеткізу, жинау және орналастыру." }, { title: "Аяқтау", description: "Соңғы орналастыруды тексеру және ашық тапсыру тармақтарын жабу." }] },
    "industrial-procurement-supply": { title: "Өнеркәсіптік сатып алу және жеткізу", description: "Клиент сипаттамалары мен құжаттама талаптарына сәйкес техникалық материалдарды жобалық негізде жеткізу.", overview: "KAZENCO жоба талаптарын талдайды, өндірушілерді үйлестіреді және сұралған сипаттама, мөлшер, құжаттама мен жеткізу орнына сай пакеттер дайындайды. Соңғы сәйкестік әр бекітілген сұрау бойынша расталады.", scope: ["Техникалық талаптарды талдау", "Өндірушілерді үйлестіру", "MTC және CoC құжаттамасы", "Жеткізуді жоспарлау"], delivery: [{ title: "Техникалық талдау", description: "Сипаттамаларды, мөлшерлерді, стандарттарды және қажетті құжаттарды тексеру." }, { title: "Жеткізушіні таңдау", description: "Сәйкес өндірушілер мен коммерциялық жеткізу шарттарын үйлестіру." }, { title: "Құжаттама", description: "Келісілген сертификаттарды, жазбалар мен материал құжаттарын жинақтау." }, { title: "Жеткізу", description: "Қаптама, тасымалдау және жеткізуді бекітілген кесте бойынша жоспарлау." }] },
    "environmental-geosynthetic-works": { title: "Экологиялық және геосинтетикалық жұмыстар", description: "Өнеркәсіптік және азаматтық инфрақұрылымға арналған қорғаныш жер жүйелері мен геосинтетикалық шешімдер.", overview: "Қорғаныш төсемдері, негіз және оқшаулау жұмыстары белгіленген алаң құрылымы мен монтаж ретіне сай үйлестіріледі. Жұмыс шебінің үздіксіздігі үшін көлем көршілес азаматтық және құрылымдық жұмыстармен сәйкестендіріледі.", scope: ["Жер төсемі жүйелері", "Қорғаныш негіз қабаттары", "Оқшаулау жұмыстары", "Монтажды қолдау"], delivery: [{ title: "Жүйені талдау", description: "Қабат құрылымын, түйісулерді және монтаж аумағын тексеру." }, { title: "Материалдарды жоспарлау", description: "Бекітілген материалдарды, мөлшерлерді және жұмыс шебінің дайындығын үйлестіру." }, { title: "Қолдану", description: "Келісілген қорғаныш қабаттарын көршілес жұмыстармен ретімен орнату." }, { title: "Жабу", description: "Аяқталған аумақтар мен монтаж жазбаларын тексеру." }] },
  },
};

export function getLocalizedCapability(slug: string, locale: Locale): Capability | undefined {
  const capability = getCapability(slug);
  if (!capability || locale === "en") return capability;
  const translation = TRANSLATIONS[locale][slug];
  return translation ? { ...capability, ...translation } : capability;
}
