import type { Locale } from "@/lib/i18n";

interface HomeCopy {
  skip: string;
  hero: {
    eyebrow: string;
    title: [string, string, string];
    lead: string;
    quote: string;
    projects: string;
    catalog: string;
    stats: [string, string, string];
    clients: string;
  };
  about: {
    kicker: string;
    title: string;
    text: string;
    cite: string;
    button: string;
    affiliate: { label: string; text: string; link: string; ariaLabel: string };
  };
  why: { kicker: string; title: string; reasons: Array<[string, string, string]> };
  industries: { kicker: string; title: string; intro: string; items: Array<[string, string, string]> };
  faq: { kicker: string; title: string; intro: string; contact: string; items: Array<[string, string]> };
  contact: { kicker: string; intro: string; button: string; labels: [string, string, string]; location: string };
}

export const HOME_COPY: Record<Locale, HomeCopy> = {
  en: {
    skip: "Skip to main content",
    hero: { eyebrow: "Engineering · Procurement · Construction", title: ["Building", "Industrial", "Excellence."], lead: "Engineering, procurement, construction and industrial supply solutions for complex projects across Kazakhstan.", quote: "Request a quotation", projects: "Explore projects", catalog: "Download Catalog", stats: ["Years of experience", "Client organisations", "Project references"], clients: "Selected client organisations" },
    about: { kicker: "Who we are", title: "More than two decades of project delivery", text: "Since 2004, KAZENCO has supported operators, contractors and project teams with coordinated construction, fit-out, furnishing and industrial supply solutions across Kazakhstan.", cite: "— KAZENCO, established in Atyrau in 2004", button: "Discover KAZENCO", affiliate: { label: "Türkiye Affiliate", text: "DOKA is KAZENCO’s affiliate in Türkiye. DOKA’s technical sourcing and manufacturer coordination capabilities in Türkiye complement KAZENCO’s project execution and local coordination experience in Kazakhstan.", link: "DOKA Foreign Trade", ariaLabel: "Open the DOKA Foreign Trade website" } },
    why: { kicker: "Why KAZENCO", title: "Local knowledge. International project discipline.", reasons: [["Two decades of regional experience", "Established in Atyrau in 2004, with project delivery knowledge built across Kazakhstan’s key industrial regions.", "01"], ["Integrated delivery model", "Engineering support, procurement, construction, fit-out, furnishing and material supply coordinated by one team.", "02"], ["Multilingual technical communication", "Commercial and technical coordination in English, Russian, Turkish and Kazakh.", "03"], ["Documentation-led supply", "Project requirements supported with manufacturer documentation, certificates, inspection records and traceability.", "04"]] },
    industries: { kicker: "Industries we serve", title: "Built for demanding operating environments.", intro: "Supporting operators, EPC contractors and project teams with coordinated supply and delivery across Kazakhstan.", items: [["Oil & Gas", "Supply and project support for upstream, midstream and downstream requirements.", "01"], ["Petrochemical", "Materials and coordinated delivery for process plants and industrial facilities.", "02"], ["Energy", "Project supply packages for power generation and supporting infrastructure.", "03"], ["Industrial Facilities", "Construction, fit-out, furnishing and technical materials for operational sites.", "04"], ["Infrastructure", "Coordinated material supply and site support for regional development projects.", "05"], ["Commercial & Hospitality", "Turnkey furnishing, fit-out and material supply for offices and hotels.", "06"]] },
    faq: { kicker: "FAQ", title: "Answers to common questions", intro: "Need additional information?", contact: "Contact our team.", items: [["How can I request a quotation?", "Use the quotation form with your service type, project location, required date and technical scope. You may also add drawings, quantities and specifications."], ["Which industries does KAZENCO serve?", "We support oil and gas, petrochemical, energy, construction, infrastructure, hospitality and industrial projects across Kazakhstan."], ["What products can KAZENCO supply?", "Our scope includes industrial piping materials, stainless steel pipes and fittings, connection components, electrical equipment, construction materials and furniture."], ["Does KAZENCO provide turnkey services?", "Yes. We coordinate construction, fit-out, furnishing, material supply and installation as turnkey project packages."]] },
    contact: { kicker: "Contact", intro: "Contact our headquarters for company information, project enquiries and general assistance.", button: "Create an RFQ", labels: ["Headquarters Office", "General Enquiries", "Telephone"], location: "7 Kazyna 2-1\nAtyrau, 060000, Kazakhstan" },
  },
  ru: {
    skip: "Перейти к основному содержанию",
    hero: { eyebrow: "Инжиниринг · Закупки · Строительство", title: ["Создаём", "промышленное", "совершенство."], lead: "Инжиниринговые, закупочные, строительные решения и промышленные поставки для сложных проектов по всему Казахстану.", quote: "Запросить предложение", projects: "Смотреть проекты", catalog: "Скачать каталог", stats: ["Лет опыта", "Представленных организаций-клиентов", "Реализованных проектов"], clients: "Избранные клиенты" },
    about: { kicker: "О компании", title: "Более двадцати лет реализации проектов", text: "С 2004 года KAZENCO оказывает поддержку операторам, подрядчикам и проектным командам, предоставляя комплексные услуги строительства, отделки, оснащения и промышленных поставок по всему Казахстану.", cite: "— KAZENCO, основана в Атырау в 2004 году", button: "Узнать о KAZENCO", affiliate: { label: "Аффилированная компания в Турции", text: "DOKA является аффилированной компанией KAZENCO в Турции. Возможности DOKA в области технических закупок и координации с производителями в Турции дополняют опыт KAZENCO в реализации проектов и локальной координации в Казахстане.", link: "DOKA Foreign Trade", ariaLabel: "Открыть сайт DOKA Foreign Trade" } },
    why: { kicker: "Почему KAZENCO", title: "Знание региона. Международная проектная дисциплина.", reasons: [["Двадцать лет регионального опыта", "Компания основана в Атырау в 2004 году и обладает опытом работы в ключевых промышленных регионах Казахстана.", "01"], ["Интегрированная модель реализации", "Инжиниринг, закупки, строительство, отделка, оснащение и поставки координируются одной командой.", "02"], ["Многоязычная техническая коммуникация", "Коммерческое и техническое взаимодействие на английском, русском, турецком и казахском языках.", "03"], ["Поставки на основе документации", "Требования проекта подтверждаются документацией производителей, сертификатами, инспекционными отчётами и прослеживаемостью.", "04"]] },
    industries: { kicker: "Отрасли", title: "Решения для сложных условий эксплуатации.", intro: "Координированные поставки и реализация проектов для операторов, EPC-подрядчиков и проектных команд по всему Казахстану.", items: [["Нефть и газ", "Поставки и проектная поддержка для upstream, midstream и downstream задач.", "01"], ["Нефтехимия", "Материалы и координированные поставки для технологических установок и промышленных объектов.", "02"], ["Энергетика", "Комплектные поставки для генерации энергии и сопутствующей инфраструктуры.", "03"], ["Промышленные объекты", "Строительство, отделка, оснащение и технические материалы для действующих площадок.", "04"], ["Инфраструктура", "Поставки материалов и поддержка площадок для региональных проектов развития.", "05"], ["Коммерция и гостиничный сектор", "Отделка, меблировка и поставка материалов под ключ для офисов и гостиниц.", "06"]] },
    faq: { kicker: "Частые вопросы", title: "Ответы на частые вопросы", intro: "Нужна дополнительная информация?", contact: "Свяжитесь с нашей командой.", items: [["Как запросить коммерческое предложение?", "Заполните форму, указав вид услуги, место проекта, требуемую дату и технический объём. Также можно добавить чертежи, объёмы и спецификации."], ["В каких отраслях работает KAZENCO?", "Мы поддерживаем нефтегазовые, нефтехимические, энергетические, строительные, инфраструктурные, гостиничные и промышленные проекты в Казахстане."], ["Какую продукцию поставляет KAZENCO?", "В объём поставок входят трубопроводные материалы, нержавеющие трубы и фитинги, соединительные элементы, электрооборудование, строительные материалы и мебель."], ["Предоставляет ли KAZENCO услуги под ключ?", "Да. Мы объединяем строительство, отделку, оснащение, поставку материалов и монтаж в единые проектные пакеты."]] },
    contact: { kicker: "Контакты", intro: "Обратитесь в наш головной офис за информацией о компании, по проектным запросам и общим вопросам.", button: "Создать запрос", labels: ["Головной офис", "Общие вопросы", "Телефон"], location: "7 Kazyna 2-1\nAtyrau, 060000, Kazakhstan" },
  },
  tr: {
    skip: "Ana içeriğe geç",
    hero: { eyebrow: "Mühendislik · Tedarik · İnşaat", title: ["Endüstriyel", "mükemmelliği", "inşa ediyoruz."], lead: "Kazakistan genelindeki karmaşık projeler için mühendislik, tedarik, inşaat ve endüstriyel malzeme çözümleri.", quote: "Teklif talep et", projects: "Projeleri incele", catalog: "Kataloğu İndir", stats: ["Yılı aşkın deneyim", "Kurumsal müşteri", "Proje referansı"], clients: "Seçili müşteri kuruluşları" },
    about: { kicker: "Biz kimiz", title: "Yirmi yılı aşan proje deneyimi", text: "KAZENCO, 2004 yılından bu yana Kazakistan genelinde işletmecilere, yüklenicilere ve proje ekiplerine koordineli inşaat, ince işler, mobilya ve endüstriyel tedarik çözümleri sunmaktadır.", cite: "— KAZENCO, 2004 yılında Atırau’da kuruldu", button: "KAZENCO’yu keşfet", affiliate: { label: "Türkiye İştiraki", text: "DOKA, KAZENCO’nun Türkiye iştirakidir. DOKA’nın Türkiye’deki teknik tedarik ve üretici koordinasyonu, KAZENCO’nun Kazakistan’daki proje uygulama ve yerel koordinasyon deneyimini tamamlar.", link: "DOKA Dış Ticaret", ariaLabel: "DOKA Dış Ticaret web sitesini aç" } },
    why: { kicker: "Neden KAZENCO", title: "Yerel bilgi. Uluslararası proje disiplini.", reasons: [["Yirmi yılı aşkın bölgesel deneyim", "2004 yılında Atırau’da kurulan KAZENCO, Kazakistan’ın başlıca sanayi bölgelerinde proje uygulama deneyimine sahiptir.", "01"], ["Entegre proje uygulama modeli", "Mühendislik desteği, satın alma, inşaat, ince işler, mobilya ve malzeme tedariki tek ekip tarafından koordine edilir.", "02"], ["Çok dilli teknik iletişim", "İngilizce, Rusça, Türkçe ve Kazakça ticari ve teknik koordinasyon.", "03"], ["Dokümantasyon odaklı tedarik", "Proje gereksinimleri üretici belgeleri, sertifikalar, muayene kayıtları ve izlenebilirlikle desteklenir.", "04"]] },
    industries: { kicker: "Hizmet verdiğimiz sektörler", title: "Zorlu çalışma koşulları için güçlü çözümler.", intro: "Kazakistan genelinde işletmecilere, EPC yüklenicilerine ve proje ekiplerine koordineli tedarik ve proje uygulama desteği.", items: [["Petrol ve Gaz", "Üretim, taşıma ve işleme ihtiyaçları için tedarik ve proje desteği.", "01"], ["Petrokimya", "Proses tesisleri ve sanayi yapıları için malzeme ve koordineli teslimat.", "02"], ["Enerji", "Enerji üretimi ve destek altyapısı için proje tedarik paketleri.", "03"], ["Endüstriyel Tesisler", "Operasyon sahaları için inşaat, ince işler, mobilya ve teknik malzemeler.", "04"], ["Altyapı", "Bölgesel kalkınma projeleri için koordineli malzeme tedariki ve saha desteği.", "05"], ["Ticari Yapılar ve Konaklama", "Ofisler ve oteller için anahtar teslim ince işler, mobilya ve malzeme tedariki.", "06"]] },
    faq: { kicker: "Sık Sorulan Sorular", title: "Merak edilenler", intro: "Daha fazla bilgiye mi ihtiyacınız var?", contact: "Ekibimizle iletişime geçin.", items: [["Nasıl teklif talep edebilirim?", "Hizmet türü, proje konumu, gerekli tarih ve teknik kapsamı belirterek teklif formunu doldurun. Çizim, metraj ve şartnameleri de ekleyebilirsiniz."], ["KAZENCO hangi sektörlere hizmet veriyor?", "Kazakistan genelinde petrol ve gaz, petrokimya, enerji, inşaat, altyapı, konaklama ve sanayi projelerini destekliyoruz."], ["KAZENCO hangi ürünleri tedarik edebilir?", "Endüstriyel borulama malzemeleri, paslanmaz boru ve bağlantı parçaları, bağlantı elemanları, elektrik ekipmanları, yapı malzemeleri ve mobilya tedarik ediyoruz."], ["KAZENCO anahtar teslim hizmet veriyor mu?", "Evet. İnşaat, ince işler, mobilya, malzeme tedariki ve montajı koordineli anahtar teslim paketler halinde sunuyoruz."]] },
    contact: { kicker: "İletişim", intro: "Şirket bilgileri, proje talepleri ve genel destek için merkez ofisimizle iletişime geçin.", button: "Teklif talebi oluştur", labels: ["Merkez Ofis", "Genel Talepler", "Telefon"], location: "7 Kazyna 2-1\nAtyrau, 060000, Kazakhstan" },
  },
  kz: {
    skip: "Негізгі мазмұнға өту",
    hero: { eyebrow: "Инжиниринг · Сатып алу · Құрылыс", title: ["Өнеркәсіптік", "кемелдікті", "қалыптастырамыз."], lead: "Қазақстандағы күрделі жобаларға арналған инжиниринг, сатып алу, құрылыс және өнеркәсіптік жабдықтау шешімдері.", quote: "Баға ұсынысын сұрау", projects: "Жобаларды қарау", catalog: "Каталогты жүктеу", stats: ["Жылдық тәжірибе", "Ұсынылған клиент ұйымдары", "Жоба тәжірибесі"], clients: "Таңдаулы клиент ұйымдары" },
    about: { kicker: "Біз туралы", title: "Жиырма жылдан астам жобалық тәжірибе", text: "2004 жылдан бері KAZENCO Қазақстан бойынша операторларға, мердігерлерге және жоба топтарына құрылыс, әрлеу, жиһаздандыру және өнеркәсіптік жабдықтау шешімдерін ұсынып келеді.", cite: "— KAZENCO, 2004 жылы Атырауда құрылған", button: "KAZENCO туралы білу", affiliate: { label: "Түркиядағы аффилирленген компания", text: "DOKA — KAZENCO-ның Түркиядағы аффилирленген компаниясы. DOKA-ның Түркиядағы техникалық жабдықтау және өндірушілермен үйлестіру мүмкіндіктері KAZENCO-ның Қазақстандағы жобаларды іске асыру және жергілікті үйлестіру тәжірибесін толықтырады.", link: "DOKA Foreign Trade", ariaLabel: "DOKA Foreign Trade веб-сайтын ашу" } },
    why: { kicker: "Неліктен KAZENCO", title: "Жергілікті білім. Халықаралық жобалық тәртіп.", reasons: [["Жиырма жылдық өңірлік тәжірибе", "2004 жылы Атырауда құрылған компания Қазақстанның негізгі өнеркәсіптік өңірлерінде жинақталған тәжірибеге ие.", "01"], ["Біріктірілген орындау үлгісі", "Инжиниринг, сатып алу, құрылыс, әрлеу, жиһаздандыру және материал жеткізуді бір команда үйлестіреді.", "02"], ["Көптілді техникалық байланыс", "Ағылшын, орыс, түрік және қазақ тілдеріндегі коммерциялық және техникалық үйлестіру.", "03"], ["Құжаттамаға негізделген жабдықтау", "Жоба талаптары өндіруші құжаттарымен, сертификаттармен, тексеру жазбаларымен және қадағаланумен расталады.", "04"]] },
    industries: { kicker: "Қызмет көрсететін салалар", title: "Күрделі жұмыс жағдайларына арналған.", intro: "Қазақстан бойынша операторларға, EPC мердігерлеріне және жоба топтарына үйлестірілген жеткізу мен орындау қызметтері.", items: [["Мұнай және газ", "Өндіру, тасымалдау және өңдеу талаптарына арналған жабдықтау мен жобалық қолдау.", "01"], ["Мұнай-химия", "Технологиялық қондырғылар мен өнеркәсіптік нысандарға арналған материалдар және үйлестірілген жеткізу.", "02"], ["Энергетика", "Энергия өндіру және қосалқы инфрақұрылымға арналған жабдықтау пакеттері.", "03"], ["Өнеркәсіптік нысандар", "Өндірістік алаңдарға арналған құрылыс, әрлеу, жиһаз және техникалық материалдар.", "04"], ["Инфрақұрылым", "Өңірлік даму жобаларына арналған материал жеткізу және алаңдық қолдау.", "05"], ["Коммерция және қонақжайлылық", "Кеңселер мен қонақүйлерге арналған толық жиһаздандыру, әрлеу және материал жеткізу.", "06"]] },
    faq: { kicker: "Жиі қойылатын сұрақтар", title: "Жиі қойылатын сұрақтар", intro: "Қосымша ақпарат қажет пе?", contact: "Біздің командаға хабарласыңыз.", items: [["Баға ұсынысын қалай сұрауға болады?", "Қызмет түрін, жоба орнын, қажетті күнді және техникалық көлемді көрсетіп, ұсыныс формасын толтырыңыз. Сызбалар, көлемдер мен сипаттамаларды да қосуға болады."], ["KAZENCO қандай салаларда жұмыс істейді?", "Қазақстандағы мұнай-газ, мұнай-химия, энергетика, құрылыс, инфрақұрылым, қонақжайлылық және өнеркәсіп жобаларын қолдаймыз."], ["KAZENCO қандай өнімдерді жеткізеді?", "Өнеркәсіптік құбыр материалдарын, тот баспайтын құбырлар мен фитингтерді, бекіту бөлшектерін, электр жабдықтарын, құрылыс материалдары мен жиһазды жеткіземіз."], ["KAZENCO толық циклді қызмет көрсете ме?", "Иә. Құрылыс, әрлеу, жиһаздандыру, материал жеткізу және монтажды бірыңғай жоба пакеттері ретінде үйлестіреміз."]] },
    contact: { kicker: "Байланыс", intro: "Компания туралы ақпарат, жобалық сұраулар және жалпы көмек үшін бас кеңсемізге хабарласыңыз.", button: "Сұрау жіберу", labels: ["Бас кеңсе", "Жалпы сұраулар", "Телефон"], location: "7 Kazyna 2-1\nAtyrau, 060000, Kazakhstan" },
  },
};
