import type { Locale } from "@/lib/i18n";

export const RFQ_COPY: Record<Locale, string[]> = {
  en: ["Request for quotation", "Tell us what the project requires.", "Add project details, drawings, BOQs and specifications. Secure delivery will activate after email-domain verification.", "RFQ email", "Contact details", "Name", "Work email", "Company", "Telephone", "Requirement", "Project name", "Request type", "Select a service", "Project location", "Required delivery or start date", "Scope & specifications", "Requirement details", "Specifications, standards or quantities", "Technical files", "Drawings", "BOQ / quantities", "Specifications", "Up to 8 files · 15 MB per file · 40 MB combined", "Remove", "I agree that KAZENCO may use these details to review and respond to this enquiry.", "Uploading technical files", "Submitting quotation request…", "Request received", "Secure delivery is not active yet. Attach the selected files to the prepared email.", "The email draft could not be opened. Please use the RFQ email shown here.", "Submit RFQ", "Uploading", "Submitting…"],
  ru: ["Запрос коммерческого предложения", "Расскажите, что требуется проекту.", "Добавьте сведения о проекте, чертежи, ведомости объёмов и спецификации. Безопасная отправка активируется после проверки почтового домена.", "Email для RFQ", "Контактные данные", "Имя", "Рабочий email", "Компания", "Телефон", "Требование", "Название проекта", "Тип запроса", "Выберите услугу", "Место проекта", "Требуемая дата поставки или начала", "Объём и спецификации", "Описание требования", "Спецификации, стандарты или объёмы", "Технические файлы", "Чертежи", "Ведомость объёмов", "Спецификации", "До 8 файлов · 15 МБ на файл · всего 40 МБ", "Удалить", "Я согласен на использование этих данных KAZENCO для рассмотрения запроса и ответа.", "Загрузка технических файлов", "Отправка запроса…", "Запрос получен", "Безопасная отправка ещё не активна. Приложите выбранные файлы к подготовленному письму.", "Не удалось открыть черновик письма. Используйте указанный адрес RFQ.", "Отправить RFQ", "Загрузка", "Отправка…"],
  tr: ["Teklif talebi", "Projenin neye ihtiyacı olduğunu anlatın.", "Proje bilgilerini, çizimleri, BOQ dosyalarını ve şartnameleri ekleyin. Güvenli gönderim e-posta alan adı doğrulandıktan sonra etkinleşecektir.", "RFQ e-postası", "İletişim bilgileri", "Ad soyad", "İş e-postası", "Şirket", "Telefon", "Talep", "Proje adı", "Talep türü", "Hizmet seçin", "Proje konumu", "Gerekli teslimat veya başlangıç tarihi", "Kapsam ve şartnameler", "Talep ayrıntıları", "Şartnameler, standartlar veya miktarlar", "Teknik dosyalar", "Çizimler", "BOQ / metraj", "Şartnameler", "En fazla 8 dosya · dosya başına 15 MB · toplam 40 MB", "Kaldır", "KAZENCO’nun bu bilgileri talebimi incelemek ve yanıtlamak için kullanmasını kabul ediyorum.", "Teknik dosyalar yükleniyor", "Teklif talebi gönderiliyor…", "Talep alındı", "Güvenli gönderim henüz aktif değil. Seçilen dosyaları hazırlanan e-postaya ekleyin.", "E-posta taslağı açılamadı. Lütfen gösterilen RFQ adresini kullanın.", "RFQ gönder", "Yükleniyor", "Gönderiliyor…"],
  kz: ["Баға ұсынысына сұрау", "Жобаға не қажет екенін айтыңыз.", "Жоба мәліметтерін, сызбаларды, BOQ файлдарын және сипаттамаларды қосыңыз. Қауіпсіз жіберу пошта домені расталғаннан кейін іске қосылады.", "RFQ электрондық поштасы", "Байланыс деректері", "Аты-жөні", "Жұмыс электрондық поштасы", "Компания", "Телефон", "Талап", "Жоба атауы", "Сұрау түрі", "Қызметті таңдаңыз", "Жоба орны", "Қажетті жеткізу немесе басталу күні", "Көлем және сипаттамалар", "Талаптың егжей-тегжейі", "Сипаттамалар, стандарттар немесе көлемдер", "Техникалық файлдар", "Сызбалар", "BOQ / көлемдер", "Сипаттамалар", "8 файлға дейін · әр файл 15 МБ · жалпы 40 МБ", "Жою", "KAZENCO осы деректерді сұрауды қарау және жауап беру үшін пайдалануына келісемін.", "Техникалық файлдар жүктелуде", "Сұрау жіберілуде…", "Сұрау қабылданды", "Қауіпсіз жіберу әлі белсенді емес. Таңдалған файлдарды дайындалған хатқа тіркеңіз.", "Хат жобасы ашылмады. Көрсетілген RFQ мекенжайын пайдаланыңыз.", "RFQ жіберу", "Жүктелуде", "Жіберілуде…"],
};

export const SERVICE_LABELS: Record<Locale, string[]> = {
  en: ["Construction & Site Works", "Fit-out & Furnishing", "Industrial Procurement & Supply", "Environmental & Geosynthetic Works", "General Project Enquiry"],
  ru: ["Строительные и площадочные работы", "Отделка и оснащение", "Промышленные закупки и поставки", "Экологические и геосинтетические работы", "Общий проектный запрос"],
  tr: ["İnşaat ve saha işleri", "İnce işler ve mobilya", "Endüstriyel tedarik ve satın alma", "Çevresel ve geosentetik işler", "Genel proje talebi"],
  kz: ["Құрылыс және алаң жұмыстары", "Әрлеу және жиһаздандыру", "Өнеркәсіптік сатып алу және жеткізу", "Экологиялық және геосинтетикалық жұмыстар", "Жалпы жобалық сұрау"],
};

export const ABOUT_COPY: Record<Locale, string[]> = {
  en: ["About KAZENCO", "Integrated construction, fit-out, furnishing and industrial material supply for projects across Kazakhstan.", "About Us", "Engineering Excellence Since 2004", "Our Delivery Model", "Company Highlights", "Industries We Serve", "Capabilities", "Supply Categories", "Our Clients", "Contact"],
  ru: ["О KAZENCO", "Комплексное строительство, отделка, оснащение и поставка промышленных материалов для проектов по всему Казахстану.", "О нас", "Инженерное совершенство с 2004 года", "Наша модель реализации", "Основные факты", "Отрасли", "Возможности", "Категории поставок", "Наши клиенты", "Контакты"],
  tr: ["KAZENCO hakkında", "Kazakistan genelindeki projeler için bütünleşik inşaat, ince işler, mobilya ve endüstriyel malzeme tedariki.", "Hakkımızda", "2004’ten beri mühendislik mükemmelliği", "Uygulama modelimiz", "Şirketin öne çıkanları", "Hizmet verdiğimiz sektörler", "Yetkinlikler", "Tedarik kategorileri", "Müşterilerimiz", "İletişim"],
  kz: ["KAZENCO туралы", "Қазақстандағы жобаларға арналған біріктірілген құрылыс, әрлеу, жиһаздандыру және өнеркәсіптік материал жеткізу.", "Біз туралы", "2004 жылдан бергі инженерлік кемелдік", "Орындау үлгіміз", "Компанияның негізгі деректері", "Қызмет көрсететін салалар", "Мүмкіндіктер", "Жеткізу санаттары", "Клиенттеріміз", "Байланыс"],
};

export const ABOUT_CONTENT: Record<Locale, {
  paragraphs: [string, string];
  highlights: string[];
  industries: string[];
  capabilities: string[];
  delivery: Array<[string, string]>;
  supply: Array<[string, string[]]>;
  roles: string[];
  address: string;
}> = {
  en: {
    paragraphs: ["Founded in Atyrau in 2004, KAZENCO supports civil, commercial and industrial projects through construction, turnkey fit-out, furnishing and industrial material supply.", "The company coordinates site execution and supply requirements through one delivery structure, from technical review and procurement to installation and final handover. The portfolio covers Atyrau, Almaty, Tengiz, Karabatan, Aktau and Aksai, with communication in Kazakh, Russian, English and Turkish."],
    highlights: ["Established in 2004", "Based in Atyrau, Kazakhstan", "20 project references presented", "Projects across six Kazakhstan locations", "Kazakh, Russian, English & Turkish communication", "Construction, fit-out, furnishing & industrial supply"],
    industries: ["Oil & Gas", "Petrochemical Plants", "Refineries", "Energy & Power Plants", "Industrial Facilities", "Construction & Infrastructure Projects", "Commercial & Hospitality", "Manufacturing & Fabrication"],
    capabilities: ["Construction & site works", "Turnkey fit-out", "Furniture supply & installation", "Structural steel fabrication & erection", "Industrial material procurement", "Technical submittals & documentation", "Logistics & delivery coordination", "Environmental lining & geosynthetic works"],
    delivery: [["Construction & Site Works", "Civil, structural and installation scopes coordinated for active project environments."], ["Fit-out & Furnishing", "Interior completion, furniture supply, delivery and final installation as one package."], ["Industrial Supply", "Project materials sourced against technical requirements with supporting documentation."], ["Environmental Applications", "Ground-lining, insulation and geosynthetic applications for industrial infrastructure."]],
    supply: [["Office & Camp Furniture", ["Workstations", "Camp furniture", "Turnkey furnishing"]], ["Bolts & Connection Components", ["Bolts", "Fasteners", "Connection elements"]], ["Industrial Supply Solutions", ["Hand tools", "Power tools", "PPE & consumables"]], ["Stainless Steel Pipes & Fittings", ["Pipes", "Fittings", "Industrial components"]], ["Electrical Equipment & Devices", ["Panels", "Devices", "Electrical materials"]], ["Construction Materials", ["Building materials", "Site supplies", "Project procurement"]]],
    roles: ["Founder & Managing Director", "General Manager", "RFQ Contact"],
    address: "Zheti Kazyna, 2-1, Atyrau, Kazakhstan",
  },
  ru: {
    paragraphs: ["Основанная в Атырау в 2004 году компания KAZENCO поддерживает гражданские, коммерческие и промышленные проекты, выполняя строительство, отделку под ключ, оснащение и поставку промышленных материалов.", "Компания объединяет работы на площадке и поставки в единой структуре — от технического анализа и закупок до монтажа и окончательной передачи. Портфолио охватывает Атырау, Алматы, Тенгиз, Карабатан, Актау и Аксай; коммуникация ведётся на казахском, русском, английском и турецком языках."],
    highlights: ["Основана в 2004 году", "Головной офис в Атырау, Казахстан", "Представлено 20 проектных референсов", "Проекты в шести локациях Казахстана", "Общение на казахском, русском, английском и турецком", "Строительство, отделка, оснащение и промышленные поставки"],
    industries: ["Нефть и газ", "Нефтехимические заводы", "Нефтеперерабатывающие заводы", "Энергетика и электростанции", "Промышленные объекты", "Строительство и инфраструктура", "Коммерция и гостиничный сектор", "Производство и изготовление"],
    capabilities: ["Строительные и площадочные работы", "Отделка под ключ", "Поставка и монтаж мебели", "Изготовление и монтаж металлоконструкций", "Закупка промышленных материалов", "Техническая документация и согласования", "Логистика и координация доставки", "Защитные покрытия и геосинтетические работы"],
    delivery: [["Строительные и площадочные работы", "Координация гражданских, конструктивных и монтажных работ на действующих проектных площадках."], ["Отделка и оснащение", "Завершение интерьеров, поставка мебели, доставка и финальный монтаж единым пакетом."], ["Промышленные поставки", "Подбор проектных материалов по техническим требованиям с подтверждающей документацией."], ["Экологические решения", "Защитная облицовка грунта, изоляция и геосинтетика для промышленной инфраструктуры."]],
    supply: [["Офисная и вахтовая мебель", ["Рабочие места", "Вахтовая мебель", "Оснащение под ключ"]], ["Болты и соединительные элементы", ["Болты", "Крепёж", "Соединительные элементы"]], ["Промышленное снабжение", ["Ручной инструмент", "Электроинструмент", "СИЗ и расходники"]], ["Нержавеющие трубы и фитинги", ["Трубы", "Фитинги", "Промышленные компоненты"]], ["Электрооборудование", ["Щиты", "Устройства", "Электроматериалы"]], ["Строительные материалы", ["Стройматериалы", "Снабжение площадки", "Проектные закупки"]]],
    roles: ["Основатель и управляющий директор", "Генеральный директор", "Контакт по RFQ"],
    address: "Жети Казына, 2-1, Атырау, Казахстан",
  },
  tr: {
    paragraphs: ["2004 yılında Atırau’da kurulan KAZENCO; inşaat, anahtar teslim ince işler, mobilya ve endüstriyel malzeme tedarikiyle sivil, ticari ve endüstriyel projeleri destekler.", "Şirket, teknik inceleme ve satın almadan montaj ve nihai teslime kadar saha uygulamasıyla tedarik ihtiyaçlarını tek yapıda koordine eder. Portföy Atırau, Almatı, Tengiz, Karabatan, Aktau ve Aksai’yi kapsar; Kazakça, Rusça, İngilizce ve Türkçe iletişim sunulur."],
    highlights: ["2004 yılında kuruldu", "Atırau, Kazakistan merkezli", "20 proje referansı sunuluyor", "Kazakistan’da altı lokasyonda proje", "Kazakça, Rusça, İngilizce ve Türkçe iletişim", "İnşaat, ince işler, mobilya ve endüstriyel tedarik"],
    industries: ["Petrol ve Gaz", "Petrokimya Tesisleri", "Rafineriler", "Enerji ve Elektrik Santralleri", "Endüstriyel Tesisler", "İnşaat ve Altyapı Projeleri", "Ticari ve Konaklama", "Üretim ve İmalat"],
    capabilities: ["İnşaat ve saha işleri", "Anahtar teslim ince işler", "Mobilya tedarik ve montajı", "Çelik yapı imalat ve montajı", "Endüstriyel malzeme tedariki", "Teknik sunum ve dokümantasyon", "Lojistik ve teslimat koordinasyonu", "Çevresel kaplama ve geosentetik işler"],
    delivery: [["İnşaat ve Saha İşleri", "Aktif proje ortamlarında sivil, yapısal ve montaj kapsamlarının koordinasyonu."], ["İnce İşler ve Mobilya", "İç mekân tamamlama, mobilya tedariki, teslimat ve nihai montajın tek paket sunulması."], ["Endüstriyel Tedarik", "Proje malzemelerinin teknik gereksinimlere göre belgeleriyle birlikte tedarik edilmesi."], ["Çevresel Uygulamalar", "Endüstriyel altyapı için zemin kaplama, yalıtım ve geosentetik uygulamalar."]],
    supply: [["Ofis ve Kamp Mobilyası", ["Çalışma istasyonları", "Kamp mobilyası", "Anahtar teslim mobilya"]], ["Cıvata ve Bağlantı Elemanları", ["Cıvatalar", "Bağlantı elemanları", "Birleştirme parçaları"]], ["Endüstriyel Tedarik Çözümleri", ["El aletleri", "Elektrikli aletler", "KKD ve sarf malzemeleri"]], ["Paslanmaz Boru ve Fittings", ["Borular", "Fittings", "Endüstriyel bileşenler"]], ["Elektrik Ekipmanları", ["Panolar", "Cihazlar", "Elektrik malzemeleri"]], ["Yapı Malzemeleri", ["Yapı malzemeleri", "Saha ihtiyaçları", "Proje satın alma"]]],
    roles: ["Kurucu ve Genel Müdür", "Genel Müdür", "RFQ Yetkilisi"],
    address: "Zheti Kazyna, 2-1, Atırau, Kazakistan",
  },
  kz: {
    paragraphs: ["2004 жылы Атырауда құрылған KAZENCO құрылыс, толық әрлеу, жиһаздандыру және өнеркәсіптік материал жеткізу арқылы азаматтық, коммерциялық және өнеркәсіптік жобаларды қолдайды.", "Компания техникалық талдау мен сатып алудан монтаж және соңғы тапсыруға дейін алаңдағы жұмыстар мен жеткізу талаптарын бір құрылымда үйлестіреді. Портфель Атырау, Алматы, Теңіз, Қарабатан, Ақтау және Ақсай қалаларын қамтиды; байланыс қазақ, орыс, ағылшын және түрік тілдерінде жүргізіледі."],
    highlights: ["2004 жылы құрылған", "Атырау, Қазақстанда орналасқан", "20 жоба мысалы ұсынылған", "Қазақстанның алты жеріндегі жобалар", "Қазақ, орыс, ағылшын және түрік тілдерінде байланыс", "Құрылыс, әрлеу, жиһаздандыру және өнеркәсіптік жеткізу"],
    industries: ["Мұнай және газ", "Мұнай-химия зауыттары", "Мұнай өңдеу зауыттары", "Энергетика және электр станциялары", "Өнеркәсіптік нысандар", "Құрылыс және инфрақұрылым", "Коммерция және қонақжайлылық", "Өндіріс және дайындау"],
    capabilities: ["Құрылыс және алаң жұмыстары", "Толық әрлеу", "Жиһаз жеткізу және орнату", "Металл құрылымдарын дайындау және монтаждау", "Өнеркәсіптік материалдарды сатып алу", "Техникалық ұсыныстар мен құжаттама", "Логистика және жеткізуді үйлестіру", "Қоршаған ортаны қорғау және геосинтетикалық жұмыстар"],
    delivery: [["Құрылыс және алаң жұмыстары", "Белсенді жоба орталарындағы азаматтық, құрылымдық және монтаждық жұмыстарды үйлестіру."], ["Әрлеу және жиһаздандыру", "Интерьерді аяқтау, жиһаз жеткізу және соңғы монтажды бір пакетпен орындау."], ["Өнеркәсіптік жеткізу", "Жоба материалдарын техникалық талаптар мен растайтын құжаттарға сәйкес жеткізу."], ["Экологиялық шешімдер", "Өнеркәсіптік инфрақұрылымға арналған жер төсемі, оқшаулау және геосинтетикалық жұмыстар."]],
    supply: [["Кеңсе және вахталық жиһаз", ["Жұмыс орындары", "Вахталық жиһаз", "Толық жиһаздандыру"]], ["Болттар және қосқыштар", ["Болттар", "Бекіткіштер", "Қосылу бөлшектері"]], ["Өнеркәсіптік жабдықтау", ["Қол құралдары", "Электр құралдары", "ЖҚҚ және шығын материалдары"]], ["Тот баспайтын құбырлар мен фитингтер", ["Құбырлар", "Фитингтер", "Өнеркәсіптік бөлшектер"]], ["Электр жабдықтары", ["Панельдер", "Құрылғылар", "Электр материалдары"]], ["Құрылыс материалдары", ["Құрылыс материалдары", "Алаң жабдықтары", "Жобалық сатып алу"]]],
    roles: ["Құрылтайшы және басқарушы директор", "Бас директор", "RFQ байланыс тұлғасы"],
    address: "Жеті Қазына, 2-1, Атырау, Қазақстан",
  },
};
