import type { Locale } from "@/lib/i18n";

const copies = {
  en: {
    capabilities: ["Capabilities", "One delivery structure. Four connected disciplines.", "KAZENCO connects project execution and material supply so technical review, procurement, site coordination and final delivery remain aligned.", "Discuss a requirement", "View capability"],
    products: ["Core products", "Industrial supply, engineered around project requirements.", "Technical review, manufacturer coordination, documentation and delivery planning — brought together in one supply workflow.", "Reference specifications", "View supply scope", "Supply & fabrication references", "Selected material, workshop and fabricated-component photography."],
    certificates: ["Certificates & corporate records", "Proof presented with clear status.", "Current, corporate and historical documents are identified separately. Select any card to view the original PDF.", "View original PDF", "Corporate records", "Registration, tax and company-information documents.", "Quality management", "Current and historical quality-management conformity records.", "Manufacturer documents", "Authorization certificates and commercial reference documents, with dates shown transparently."],
    map: ["Project footprint", "Delivery across Kazakhstan.", "Explore twenty verified project references across six delivery locations. Select a marker to see the work completed in each area.", "All", "Construction", "Fit-out & Furnishing", "Material Supply", "Assembly", "Republic of", "Selected location", "project", "projects", "Map data is drawn from the verified project portfolio. Every location is also available through the project links and complete portfolio."],
    portfolio: ["Selected projects", "Projects presented as real case studies.", "Selected references receive a larger editorial presentation, while additional delivery references remain accessible below.", "Explore project", "Verified photography pending", "Client", "Location", "Scope", "Year", "Status", "Completed", "Other projects", "Additional construction, fit-out and industrial delivery references."],
    clients: ["Trusted by industry leaders", "Trusted relationships built through successful delivery.", "Supporting international operators, EPC contractors and regional project teams across Kazakhstan."],
    footer: ["Engineering, construction, turnkey fit-out and industrial material supply across Kazakhstan since 2004.", "Company", "About", "Projects", "Clients", "Capabilities", "Services", "Products", "Industries", "Project map", "Request a quote", "Location", "Atyrau, Kazakhstan", "English · Russian · Turkish · Kazakh", "All Rights Reserved.", "Developed by"],
  },
  ru: {
    capabilities: ["Возможности", "Единая структура реализации. Четыре взаимосвязанных направления.", "KAZENCO объединяет выполнение проектов и поставку материалов, обеспечивая согласованность технического анализа, закупок, координации площадки и финальной поставки.", "Обсудить требование", "Подробнее"],
    products: ["Основная продукция", "Промышленные поставки с учётом требований проекта.", "Технический анализ, координация производителей, документация и планирование доставки объединены в единый процесс.", "Справочные стандарты", "Смотреть объём поставки", "Примеры поставок и производства", "Избранные фотографии материалов, цехов и изготовленных компонентов."],
    certificates: ["Сертификаты и корпоративные документы", "Подтверждения с ясно указанным статусом.", "Действующие, корпоративные и архивные документы представлены отдельно. Выберите карточку, чтобы открыть оригинал PDF.", "Открыть оригинал PDF", "Корпоративные документы", "Регистрационные, налоговые и информационные документы компании.", "Управление качеством", "Действующие и архивные документы о соответствии системы качества.", "Документы производителей", "Авторизационные сертификаты и коммерческие рекомендации с прозрачным указанием дат."],
    map: ["География проектов", "Реализация по всему Казахстану.", "Двадцать подтверждённых проектов в шести локациях. Выберите маркер, чтобы увидеть выполненные работы.", "Все", "Строительство", "Отделка и оснащение", "Поставка материалов", "Монтаж", "Республика", "Выбранная локация", "проект", "проектов", "Данные карты основаны на подтверждённом портфолио. Все локации также доступны через ссылки проектов и полный портфель."],
    portfolio: ["Избранные проекты", "Проекты как реальные примеры выполненных работ.", "Ключевые проекты представлены подробно, а дополнительные референсы доступны ниже.", "Открыть проект", "Подтверждённые фотографии ожидаются", "Клиент", "Локация", "Объём", "Год", "Статус", "Завершён", "Другие проекты", "Дополнительные примеры строительства, отделки и промышленной реализации."],
    clients: ["Нам доверяют лидеры отрасли", "Доверие, заслуженное результатом.", "Поддержка международных операторов, EPC-подрядчиков и региональных проектных команд Казахстана."],
    footer: ["Инжиниринг, строительство, отделка под ключ и поставка промышленных материалов в Казахстане с 2004 года.", "Компания", "О компании", "Проекты", "Клиенты", "Возможности", "Услуги", "Продукция", "Отрасли", "Карта проектов", "Запросить предложение", "Местоположение", "Атырау, Казахстан", "Английский · Русский · Турецкий · Казахский", "Все права защищены.", "Разработано"],
  },
  tr: {
    capabilities: ["Yetkinlikler", "Tek bir uygulama modeli. Birbiriyle bağlantılı dört uzmanlık alanı.", "KAZENCO; teknik inceleme, satın alma, saha koordinasyonu ve nihai teslim süreçlerinin uyum içinde ilerlemesi için proje uygulaması ile malzeme tedarikini tek yapıda birleştirir.", "Projenizi görüşelim", "Yetkinliği incele"],
    products: ["Temel ürünler", "Proje gereksinimlerine göre şekillenen endüstriyel tedarik.", "Teknik inceleme, üretici koordinasyonu, dokümantasyon ve teslimat planlaması tek bir tedarik sürecinde yönetilir.", "Referans standartlar", "Tedarik kapsamını incele", "Tedarik ve imalat referansları", "Seçili malzeme, atölye ve imal edilmiş bileşen fotoğrafları."],
    certificates: ["Sertifikalar ve kurumsal kayıtlar", "", "Güncel, kurumsal ve geçmiş belgeler ayrı olarak gösterilir. Orijinal PDF’yi açmak için bir kart seçin.", "Orijinal PDF’yi aç", "Kurumsal kayıtlar", "Tescil, vergi ve şirket bilgi belgeleri.", "Kalite yönetimi", "Güncel ve geçmiş kalite yönetimi uygunluk kayıtları.", "Üretici belgeleri", "Tarihleri açıkça gösterilen yetki sertifikaları ve ticari referans belgeleri."],
    map: ["Faaliyet gösterdiğimiz bölgeler", "Kazakistan genelinde proje deneyimi.", "Kazakistan’daki altı farklı lokasyonda yer alan doğrulanmış yirmi proje referansını inceleyin. Her bölgedeki çalışmaları görmek için harita üzerindeki işaretçiyi seçin.", "Tümü", "İnşaat", "İnce işler ve mobilya", "Malzeme tedariki", "Montaj", "Kazakistan", "Seçili konum", "proje", "proje", "Harita verileri doğrulanmış proje portföyünden alınmıştır. Tüm konumlara proje bağlantılarından ve eksiksiz portföyden de ulaşılabilir."],
    portfolio: ["Seçili projeler", "Gerçek uygulama örnekleriyle projelerimiz.", "Öne çıkan projeler ayrıntılı olarak sunulurken diğer proje referanslarına aşağıdaki bölümden ulaşabilirsiniz.", "Projeyi incele", "Doğrulanmış fotoğraf bekleniyor", "Müşteri", "Konum", "Kapsam", "Yıl", "Durum", "Tamamlandı", "Diğer projeler", "Diğer inşaat, ince işler ve endüstriyel proje referansları."],
    clients: ["Sektör liderlerinin güveni", "Başarılı projelerle kurulan güven.", "Kazakistan genelinde uluslararası işletmeciler, EPC yüklenicileri ve bölgesel proje ekipleriyle çalışıyoruz."],
    footer: ["2004’ten beri Kazakistan genelinde mühendislik, inşaat, anahtar teslim ince işler ve endüstriyel malzeme tedariki.", "Şirket", "Hakkımızda", "Projeler", "Müşteriler", "Yetkinlikler", "Hizmetler", "Ürünler", "Sektörler", "Proje haritası", "Teklif talep et", "Konum", "Atırau, Kazakistan", "İngilizce · Rusça · Türkçe · Kazakça", "Tüm hakları saklıdır.", "Geliştiren"],
  },
  kz: {
    capabilities: ["Мүмкіндіктер", "Бір орындау құрылымы. Өзара байланысты төрт бағыт.", "KAZENCO техникалық талдау, сатып алу, алаңды үйлестіру және соңғы жеткізудің сәйкестігін қамтамасыз ету үшін жобаны орындау мен материал жеткізуді біріктіреді.", "Талапты талқылау", "Мүмкіндікті қарау"],
    products: ["Негізгі өнімдер", "Жоба талаптарына бейімделген өнеркәсіптік жабдықтау.", "Техникалық талдау, өндірушілерді үйлестіру, құжаттама және жеткізуді жоспарлау бір үдеріске біріктірілген.", "Анықтамалық стандарттар", "Жеткізу көлемін қарау", "Жеткізу және өндіріс мысалдары", "Материалдар, цехтар және дайындалған бөлшектердің таңдаулы фотосуреттері."],
    certificates: ["Сертификаттар және корпоративтік құжаттар", "Мәртебесі анық көрсетілген дәлелдер.", "Қолданыстағы, корпоративтік және тарихи құжаттар бөлек көрсетілген. Түпнұсқа PDF файлын ашу үшін картаны таңдаңыз.", "Түпнұсқа PDF файлын ашу", "Корпоративтік құжаттар", "Тіркеу, салық және компания туралы ақпараттық құжаттар.", "Сапа менеджменті", "Сапа менеджментіне сәйкестіктің қолданыстағы және тарихи жазбалары.", "Өндіруші құжаттары", "Күндері ашық көрсетілген авторизация сертификаттары мен коммерциялық анықтамалар."],
    map: ["Жобалар географиясы", "Қазақстан бойынша орындау.", "Алты жердегі расталған жиырма жобаны қараңыз. Әр аймақта орындалған жұмыстарды көру үшін белгіні таңдаңыз.", "Барлығы", "Құрылыс", "Әрлеу және жиһаз", "Материал жеткізу", "Монтаж", "Қазақстан Республикасы", "Таңдалған орын", "жоба", "жоба", "Карта деректері расталған жоба портфелінен алынған. Барлық орындар жоба сілтемелері мен толық портфельде де қолжетімді."],
    portfolio: ["Таңдаулы жобалар", "Нақты орындалған жұмыстар ретінде ұсынылған жобалар.", "Таңдаулы жобалар кеңейтілген түрде, ал қосымша тәжірибе төменде көрсетілген.", "Жобаны қарау", "Расталған фотосуреттер күтілуде", "Клиент", "Орналасқан жері", "Көлемі", "Жыл", "Мәртебе", "Аяқталған", "Басқа жобалар", "Құрылыс, әрлеу және өнеркәсіптік орындаудың қосымша мысалдары."],
    clients: ["Сала көшбасшыларының сенімі", "Нәтижемен қалыптасқан қатынастар.", "Қазақстандағы халықаралық операторларды, EPC мердігерлерін және өңірлік жоба топтарын қолдаймыз."],
    footer: ["2004 жылдан бері Қазақстан бойынша инжиниринг, құрылыс, толық әрлеу және өнеркәсіптік материал жеткізу.", "Компания", "Біз туралы", "Жобалар", "Клиенттер", "Мүмкіндіктер", "Қызметтер", "Өнімдер", "Салалар", "Жобалар картасы", "Баға ұсынысын сұрау", "Орналасқан жері", "Атырау, Қазақстан", "Ағылшын · Орыс · Түрік · Қазақ", "Барлық құқықтар қорғалған.", "Әзірлеген"],
  },
} satisfies Record<Locale, Record<string, readonly string[]>>;

export function sectionCopy(locale: Locale) {
  return copies[locale];
}
